"""
Remap question tags to the unified taxonomy defined in docs/tags-taxonomy.md.
Usage: python3 scripts/remap_tags.py
"""
import json
import glob
import copy

# ─────────────────────────────────────────────────────────────────────────────
# UNIFIED TAXONOMY (canonical tag names)
# ─────────────────────────────────────────────────────────────────────────────
MATH_TAGS = {
    "aritmética e números",
    "álgebra",
    "funções",
    "geometria plana",
    "geometria espacial",
    "geometria analítica",
    "trigonometria",
    "estatística",
    "probabilidade",
    "análise combinatória",
    "matemática financeira",
    "sequências e progressões",
}

PHYSICS_TAGS = {
    "mecânica newtoniana",
    "termologia",
    "óptica",
    "ondulatória e acústica",
    "eletricidade e magnetismo",
    "física moderna",
    "física nuclear e radioatividade",
    "gravitação e astronomia",
}

CHEMISTRY_TAGS = {
    "química geral e inorgânica",
    "química orgânica",
    "estequiometria",
    "termoquímica e cinética",
    "eletroquímica",
    "equilíbrio químico",
    "soluções e solubilidade",
}

BIOLOGY_TAGS = {
    "citologia",
    "genética e hereditariedade",
    "evolução",
    "ecologia",
    "fisiologia humana",
    "botânica",
    "zoologia",
    "microbiologia e imunologia",
    "biotecnologia",
}

HISTORY_TAGS = {
    "história do brasil colonial",
    "história do brasil imperial",
    "história do brasil república",
    "história antiga e medieval",
    "história moderna",
    "história contemporânea",
    "geopolítica e relações internacionais",
    "história da cultura e arte",
}

GEOGRAPHY_TAGS = {
    "geografia física e geologia",
    "geografia humana e urbana",
    "meio ambiente e sustentabilidade",
    "geopolítica e território",
    "cartografia",
    "climatologia",
}

PHILOSOPHY_TAGS = {
    "filosofia antiga e medieval",
    "filosofia moderna e contemporânea",
    "ética e política",
    "sociologia e estrutura social",
    "cultura e identidade",
    "direitos humanos e cidadania",
    "epistemologia e lógica",
}

LANGUAGES_TAGS = {
    "interpretação de texto",
    "gêneros textuais",
    "linguística e variação linguística",
    "literatura brasileira",
    "literatura mundial",
    "artes visuais",
    "música e dança",
    "comunicação e mídia",
    "língua espanhola",
    "língua inglesa",
}

ALL_VALID = (MATH_TAGS | PHYSICS_TAGS | CHEMISTRY_TAGS | BIOLOGY_TAGS |
             HISTORY_TAGS | GEOGRAPHY_TAGS | PHILOSOPHY_TAGS | LANGUAGES_TAGS)

# ─────────────────────────────────────────────────────────────────────────────
# MAPPING: old tag → unified tag
# None means "drop this tag"
# ─────────────────────────────────────────────────────────────────────────────
GENERAL_MAP = {
    # ── MATEMÁTICA ────────────────────────────────────────────────────────────
    "aritmética": "aritmética e números",
    "porcentagem": "aritmética e números",
    "percentagem": "aritmética e números",
    "percentual": "aritmética e números",
    "proporcionalidade": "aritmética e números",
    "proporção": "aritmética e números",
    "razão": "aritmética e números",
    "razão e proporção": "aritmética e números",
    "razões e proporções": "aritmética e números",
    "razao-e-proporcao": "aritmética e números",
    "regra de três": "aritmética e números",
    "regra de três composta": "aritmética e números",
    "números": "aritmética e números",
    "números racionais": "aritmética e números",
    "números decimais": "aritmética e números",
    "números figurados": "aritmética e números",
    "notação numérica": "aritmética e números",
    "numeração": "aritmética e números",
    "sistema de numeração": "aritmética e números",
    "divisão": "aritmética e números",
    "multiplicação": "aritmética e números",
    "subtração": "aritmética e números",
    "grandezas": "aritmética e números",
    "grandezas e unidades": "aritmética e números",
    "unidades-de-medida": "aritmética e números",
    "conversão de unidades": "aritmética e números",
    "escala": "aritmética e números",
    "comparação": "aritmética e números",
    "conceitos": "aritmética e números",

    "álgebra": "álgebra",
    "equação": "álgebra",
    "equações": "álgebra",
    "equação de segundo grau": "álgebra",
    "equação do 2º grau": "álgebra",
    "equação da reta": "álgebra",
    "sistemas de equações": "álgebra",
    "inequação": "álgebra",
    "inequações": "álgebra",
    "raciocínio algébrico": "álgebra",
    "raciocínio lógico": "álgebra",
    "modelagem matemática": "álgebra",

    "funções": "funções",
    "função": "funções",
    "função linear": "funções",
    "função quadrática": "funções",
    "função logarítmica": "funções",
    "função por partes": "funções",
    "funções trigonométricas": "funções",
    "logaritmo": "funções",
    "logaritmos": "funções",
    "otimização": "funções",

    "geometria plana": "geometria plana",
    "geometria": "geometria plana",
    "Geometria": "geometria plana",
    "Figuras Planas": "geometria plana",
    "figuras geométricas": "geometria plana",
    "circunferência": "geometria plana",
    "comprimento de circunferência": "geometria plana",
    "semicírculo": "geometria plana",
    "área": "geometria plana",
    "área de círculos": "geometria plana",
    "área de setor circular": "geometria plana",
    "área do círculo": "geometria plana",
    "área retangular": "geometria plana",
    "ângulos": "geometria plana",
    "mediatriz": "geometria plana",
    "triangulo-equilatero": "geometria plana",
    "triângulo retângulo": "geometria plana",
    "padrão geométrico": "geometria plana",
    "ampliação": "geometria plana",
    "orientação espacial": "geometria plana",
    "rotação": "geometria plana",

    "geometria espacial": "geometria espacial",
    "poliedros": "geometria espacial",
    "prisma": "geometria espacial",
    "cilindro": "geometria espacial",
    "paralelepípedo": "geometria espacial",
    "tronco de pirâmide": "geometria espacial",
    "volume": "geometria espacial",
    "planificação": "geometria espacial",
    "solidos-de-revolucao": "geometria espacial",
    "relação de Euler": "geometria espacial",
    "altitude": "geometria espacial",
    "altura": "geometria espacial",

    "geometria analítica": "geometria analítica",
    "coordenadas": "geometria analítica",
    "parábola": "geometria analítica",
    "quadrado inscrito": "geometria analítica",
    "projeção": "geometria analítica",
    "projeções": "geometria analítica",
    "projeções ortogonais": "geometria analítica",

    "trigonometria": "trigonometria",
    "lei dos cossenos": "trigonometria",
    "resolução de triângulos": "trigonometria",
    "tangente": "trigonometria",

    "estatística": "estatística",
    "desvio padrão": "estatística",
    "mediana": "estatística",
    "média": "estatística",
    "média aritmética": "estatística",
    "medidas de dispersão": "estatística",
    "medidas de tendência central": "estatística",
    "gráfico": "estatística",
    "gráficos": "estatística",
    "leitura de gráficos": "estatística",
    "análise de gráficos": "estatística",
    "análise de dados": "estatística",
    "tabelas": "estatística",
    "leitura de infográfico": "estatística",
    "interpretação de dados": "estatística",
    "tendência": "estatística",
    "notas": "estatística",
    "epidemiologia": "estatística",

    "probabilidade": "probabilidade",
    "eventos independentes": "probabilidade",
    "sorteio": "probabilidade",
    "jogo": "probabilidade",
    "torneio": "probabilidade",

    "análise combinatória": "análise combinatória",
    "arranjo": "análise combinatória",
    "combinatória": "análise combinatória",
    "combinatoria": "análise combinatória",
    "combinação": "análise combinatória",
    "permutação": "análise combinatória",
    "princípio multiplicativo": "análise combinatória",
    "senha": "análise combinatória",

    "matemática financeira": "matemática financeira",
    "matemática-financeira": "matemática financeira",
    "juros": "matemática financeira",
    "desconto": "matemática financeira",
    "financiamento": "matemática financeira",
    "finanças": "matemática financeira",
    "financeiro": "matemática financeira",
    "custo": "matemática financeira",
    "custos": "matemática financeira",
    "preço": "matemática financeira",
    "preços": "matemática financeira",
    "taxa percentual": "matemática financeira",
    "balança comercial": "matemática financeira",

    "progressão aritmética": "sequências e progressões",
    "sequência": "sequências e progressões",
    "sequências": "sequências e progressões",
    "sequência matemática": "sequências e progressões",
    "cronologia": "sequências e progressões",

    # ── FÍSICA ────────────────────────────────────────────────────────────────
    "cinemática": "mecânica newtoniana",
    "dinâmica": "mecânica newtoniana",
    "mecânica": "mecânica newtoniana",
    "força": "mecânica newtoniana",
    "força de atrito": "mecânica newtoniana",
    "força gravitacional": "mecânica newtoniana",
    "movimento": "mecânica newtoniana",
    "velocidade": "mecânica newtoniana",
    "velocidade média": "mecânica newtoniana",
    "centro de massa": "mecânica newtoniana",
    "plano inclinado": "mecânica newtoniana",
    "vetores": "mecânica newtoniana",
    "oscilações": "mecânica newtoniana",
    "movimento tridimensional": "mecânica newtoniana",
    "segurança veicular": "mecânica newtoniana",
    "avião": "mecânica newtoniana",
    "tribologia": "mecânica newtoniana",
    "combustão interna": "mecânica newtoniana",
    "motor de combustão interna": "mecânica newtoniana",
    "hidrostática": "mecânica newtoniana",
    "pressão": "mecânica newtoniana",
    "densidade": "mecânica newtoniana",

    "termologia": "termologia",
    "termometria": "termologia",
    "calor": "termologia",
    "temperatura": "termologia",
    "transferência de calor": "termologia",
    "isolamento térmico": "termologia",
    "gases ideais": "termologia",
    "gás perfeito": "termologia",
    "gases": "termologia",
    "poluição térmica": "termologia",

    "óptica": "óptica",
    "optica": "óptica",
    "refração": "óptica",
    "espelhos": "óptica",
    "fenômeno óptico": "óptica",
    "fotoluminescência": "óptica",
    "visão": "óptica",
    "olho humano": "óptica",
    "LED": "óptica",

    "ondulatória": "ondulatória e acústica",
    "ondas": "ondulatória e acústica",
    "som": "ondulatória e acústica",
    "acústica": "ondulatória e acústica",
    "ressonância": "ondulatória e acústica",

    "eletricidade": "eletricidade e magnetismo",
    "circuito": "eletricidade e magnetismo",
    "circuitos": "eletricidade e magnetismo",
    "circuito elétrico": "eletricidade e magnetismo",
    "circuitos elétricos": "eletricidade e magnetismo",
    "associação de circuitos": "eletricidade e magnetismo",
    "corrente elétrica": "eletricidade e magnetismo",
    "resistores": "eletricidade e magnetismo",
    "resistência elétrica": "eletricidade e magnetismo",
    "lei de Ohm": "eletricidade e magnetismo",
    "campo elétrico": "eletricidade e magnetismo",
    "movimento de cargas": "eletricidade e magnetismo",
    "potência elétrica": "eletricidade e magnetismo",
    "efeito Joule": "eletricidade e magnetismo",
    "eletromagnetismo": "eletricidade e magnetismo",
    "indução eletromagnética": "eletricidade e magnetismo",
    "magnetismo": "eletricidade e magnetismo",
    "ondas eletromagnéticas": "eletricidade e magnetismo",
    "espectro eletromagnético": "eletricidade e magnetismo",
    "comunicação sem fio": "eletricidade e magnetismo",
    "geradores": "eletricidade e magnetismo",
    "eletrônica": "eletricidade e magnetismo",
    "grafeno": "eletricidade e magnetismo",

    "relatividade": "física moderna",
    "física moderna": "física moderna",

    "radioatividade": "física nuclear e radioatividade",
    "energia nuclear": "física nuclear e radioatividade",
    "decaimento radioativo": "física nuclear e radioatividade",
    "meia-vida": "física nuclear e radioatividade",
    "raios-x": "física nuclear e radioatividade",
    "irradiação": "física nuclear e radioatividade",
    "radiação": "física nuclear e radioatividade",

    "gravitação": "gravitação e astronomia",
    "astronomia": "gravitação e astronomia",
    "estrelas": "gravitação e astronomia",
    "Buraco Negro": "gravitação e astronomia",
    "escala_richter": "gravitação e astronomia",
    "terremotos": "gravitação e astronomia",

    # ── QUÍMICA ───────────────────────────────────────────────────────────────
    "química": "química geral e inorgânica",
    "elementos químicos": "química geral e inorgânica",
    "ligações químicas": "química geral e inorgânica",
    "reações ácido-base": "química geral e inorgânica",
    "oxidação": "química geral e inorgânica",
    "notação química": "química geral e inorgânica",
    "funções inorgânicas": "química geral e inorgânica",
    "propriedades dos ácidos": "química geral e inorgânica",
    "história da química": "química geral e inorgânica",
    "alumínio": "química geral e inorgânica",
    "mercúrio": "química geral e inorgânica",
    "bauxita": "química geral e inorgânica",
    "neutralização": "química geral e inorgânica",
    "adsorção": "química geral e inorgânica",
    "polaridade": "química geral e inorgânica",
    "eletronegatividade": "química geral e inorgânica",
    "interações intermoleculares": "química geral e inorgânica",
    "interações moleculares": "química geral e inorgânica",
    "estrutura molecular": "química geral e inorgânica",
    "reações químicas": "química geral e inorgânica",
    "equações químicas": "química geral e inorgânica",
    "elementos": "química geral e inorgânica",
    "poluentes": "química geral e inorgânica",
    "microplásticos": "química geral e inorgânica",
    "organoclorado": "química geral e inorgânica",
    "metano": "química geral e inorgânica",
    "gasolina": "química geral e inorgânica",
    "combustíveis": "química geral e inorgânica",
    "organometalica": "química geral e inorgânica",
    "corrosão": "química geral e inorgânica",

    "química orgânica": "química orgânica",
    "hidrocarbonetos": "química orgânica",
    "funções orgânicas": "química orgânica",
    "reações orgânicas": "química orgânica",
    "polissacarídeos": "química orgânica",
    "carboidratos": "química orgânica",

    "estequiometria": "estequiometria",
    "balanceamento": "estequiometria",
    "massa molar": "estequiometria",
    "rendimento": "estequiometria",
    "concentração de soluções": "estequiometria",

    "termoquímica": "termoquímica e cinética",
    "cinética química": "termoquímica e cinética",
    "catálise": "termoquímica e cinética",
    "energia": "termoquímica e cinética",

    "eletroquímica": "eletroquímica",
    "potencial de redução": "eletroquímica",

    "equilíbrio químico": "equilíbrio químico",
    "princípio de Le Chatelier": "equilíbrio químico",

    "solubilidade": "soluções e solubilidade",
    "destilação": "soluções e solubilidade",
    "titulação": "soluções e solubilidade",
    "água dura": "soluções e solubilidade",
    "hidratação": "soluções e solubilidade",
    "purificação de água": "soluções e solubilidade",
    "tratamento de água": "soluções e solubilidade",
    "refrigerantes": "soluções e solubilidade",

    # ── BIOLOGIA ──────────────────────────────────────────────────────────────
    "citologia": "citologia",
    "biologia celular": "citologia",
    "células": "citologia",
    "organelas celulares": "citologia",
    "cloroplastos": "citologia",
    "celular": "citologia",
    "procariontes": "citologia",
    "fermentação": "citologia",
    "metabolismo": "citologia",
    "metabolismo energético": "citologia",
    "enzimas": "citologia",
    "bioquímica": "citologia",
    "fotossíntese": "botânica",

    "genética": "genética e hereditariedade",
    "genética molecular": "genética e hereditariedade",
    "herança genética": "genética e hereditariedade",
    "hereditariedade": "genética e hereditariedade",
    "cruzamento": "genética e hereditariedade",
    "mosaicismo": "genética e hereditariedade",
    "síndrome de down": "genética e hereditariedade",
    "genotoxicidade": "genética e hereditariedade",
    "PCR": "genética e hereditariedade",
    "micronúcleos": "genética e hereditariedade",

    "evolução": "evolução",
    "adaptação": "evolução",

    "ecologia": "ecologia",
    "cadeia alimentar": "ecologia",
    "ciclo do nitrogênio": "ecologia",
    "Ciclo do nitrogênio": "ecologia",
    "biomas": "ecologia",
    "biomas brasileiros": "ecologia",
    "biodiversidade": "ecologia",
    "espécies invasoras": "ecologia",
    "espécies exóticas": "ecologia",
    "biorremediação": "ecologia",
    "fitorremediação": "ecologia",
    "biocarvão": "ecologia",
    "biodigestão": "ecologia",
    "biogás": "ecologia",
    "biomassa": "ecologia",
    "poluição": "ecologia",
    "solos": "ecologia",
    "reciclagem": "ecologia",
    "biologia": None,  # too generic, drop

    "fisiologia": "fisiologia humana",
    "fisiologia animal": "fisiologia humana",
    "fisiologia muscular": "fisiologia humana",
    "anatomia": "fisiologia humana",
    "sistema imune": "fisiologia humana",
    "sistema imunológico": "fisiologia humana",
    "hormônios": "fisiologia humana",
    "ciclo circadiano": "fisiologia humana",
    "ciclo menstrual": "fisiologia humana",
    "músculos": "fisiologia humana",
    "reprodução humana": "fisiologia humana",
    "reprodução animal": "fisiologia humana",
    "reprodução": "fisiologia humana",
    "odontologia": "fisiologia humana",
    "nutrição": "fisiologia humana",
    "vitaminas": "fisiologia humana",

    "botânica": "botânica",
    "anatomia vegetal": "botânica",
    "plantas": "botânica",
    "frutas": "botânica",
    "amadurecimento": "botânica",
    "abelhas": "botânica",

    "zoologia": "zoologia",
    "anfíbios": "zoologia",
    "aves": "zoologia",
    "artrópodes": "zoologia",
    "serpentes": "zoologia",
    "exoesqueleto": "zoologia",

    "microbiologia": "microbiologia e imunologia",
    "virologia": "microbiologia e imunologia",
    "bacteriologia": "microbiologia e imunologia",
    "protozoário": "microbiologia e imunologia",
    "parasitologia": "microbiologia e imunologia",
    "zoonose": "microbiologia e imunologia",
    "leishmaniose": "microbiologia e imunologia",
    "arboviroses": "microbiologia e imunologia",
    "coronavírus": "microbiologia e imunologia",
    "doenças transmissíveis": "microbiologia e imunologia",
    "doenças tropicais": "microbiologia e imunologia",
    "antimicrobianos": "microbiologia e imunologia",
    "vacinas": "microbiologia e imunologia",
    "imunologia": "microbiologia e imunologia",
    "microrganismos": "microbiologia e imunologia",

    "biotecnologia": "biotecnologia",
    "engenharia genética": "biotecnologia",
    "clonagem": "biotecnologia",
    "terapia gênica": "biotecnologia",
    "nanotecnologia": "biotecnologia",

    # ── HISTÓRIA ──────────────────────────────────────────────────────────────
    "história do brasil colonial": "história do brasil colonial",
    "história do Brasil colonial": "história do brasil colonial",
    "colonização espanhola": "história do brasil colonial",
    "escravidão indígena": "história do brasil colonial",
    "inquisição": "história do brasil colonial",
    "século xv e xvi": "história do brasil colonial",

    "história do brasil imperial": "história do brasil imperial",
    "história do Brasil imperial": "história do brasil imperial",
    "Corte Portuguesa no Brasil": "história do brasil imperial",
    "D. João VI": "história do brasil imperial",
    "Impressão Régia": "história do brasil imperial",
    "Segundo Reinado": "história do brasil imperial",
    "abolicionismo": "história do brasil imperial",
    "Lei Saraiva": "história do brasil imperial",
    "Roda dos Expostos": "história do brasil imperial",
    "Primeira República": "história do brasil imperial",

    "história do brasil república": "história do brasil república",
    "história do Brasil república": "história do brasil república",
    "Era Vargas": "história do brasil república",
    "Estado Novo": "história do brasil república",
    "DIP": "história do brasil república",
    "ditadura militar": "história do brasil república",
    "UDN": "história do brasil república",
    "golpe militar": "história do brasil república",
    "trabalhismo": "história do brasil república",
    "atentado Rua Tonelero": "história do brasil república",
    "Lei das Doze Tábuas": "história do brasil república",
    "república": "história do brasil república",

    "história antiga e medieval": "história antiga e medieval",
    "história antiga": "história antiga e medieval",
    "história medieval": "história antiga e medieval",
    "Idade Média": "história antiga e medieval",
    "idade média": "história antiga e medieval",
    "Roma": "história antiga e medieval",
    "Cruzadas": "história antiga e medieval",
    "plebeus": "história antiga e medieval",
    "universidades medievais": "história antiga e medieval",
    "cultura medieval": "história antiga e medieval",
    "Veneza": "história antiga e medieval",
    "Balcãs": "história antiga e medieval",
    "comércio mediterrâneo": "história antiga e medieval",

    "história moderna": "história moderna",
    "Iluminismo": "história moderna",
    "Revolução Francesa": "história moderna",
    "Adam Smith": "história moderna",

    "história contemporânea": "história contemporânea",
    "Primeira Guerra Mundial": "história contemporânea",
    "Muro de Berlim": "história contemporânea",
    "corrida espacial": "história contemporânea",
    "gripe espanhola": "história contemporânea",
    "século XX": "história contemporânea",
    "Black Lives Matter": "história contemporânea",
    "declaração balfour": "história contemporânea",
    "Rússia": "história contemporânea",

    "geopolítica": "geopolítica e relações internacionais",
    "geopolítica e relações internacionais": "geopolítica e relações internacionais",
    "ONU": "geopolítica e relações internacionais",
    "Mercosul": "geopolítica e relações internacionais",
    "União Europeia": "geopolítica e relações internacionais",
    "Conselho de Segurança": "geopolítica e relações internacionais",
    "imperialismo": "geopolítica e relações internacionais",
    "relações internacionais": "geopolítica e relações internacionais",
    "integração regional": "geopolítica e relações internacionais",
    "comércio internacional": "geopolítica e relações internacionais",
    "Argentina": "geopolítica e relações internacionais",
    "América Latina": "geopolítica e relações internacionais",
    "refugiados": "geopolítica e relações internacionais",
    "Rio Reno": "geopolítica e relações internacionais",
    "colonialismo": "geopolítica e relações internacionais",

    "arte": "história da cultura e arte",
    "patrimônio histórico": "história da cultura e arte",
    "patrimônio imaterial": "história da cultura e arte",
    "patrimônio": "história da cultura e arte",
    "história da dança": "história da cultura e arte",
    "história da cultura": "história da cultura e arte",
    "cultura popular": "história da cultura e arte",
    "cultura brasileira": "história da cultura e arte",
    "xilogravura": "história da cultura e arte",
    "cordel": "história da cultura e arte",
    "candomblé": "história da cultura e arte",
    "religiões afro-brasileiras": "história da cultura e arte",
    "religião afro-brasileira": "história da cultura e arte",
    "Círio de Nazaré": "história da cultura e arte",
    "Feira de São Cristóvão": "história da cultura e arte",
    "rituais": "história da cultura e arte",
    "ritual": "história da cultura e arte",
    "rito": "história da cultura e arte",
    "textos sagrados": "história da cultura e arte",
    "salvação": "história da cultura e arte",
    "religião": "história da cultura e arte",
    "tradição": "história da cultura e arte",
    "museu": "história da cultura e arte",
    "memória coletiva": "história da cultura e arte",
    "patrimônio cultural": "história da cultura e arte",
    "história": None,  # too generic — will be handled per-area
    "história do Brasil": None,  # too generic

    # ── GEOGRAFIA ─────────────────────────────────────────────────────────────
    "geologia": "geografia física e geologia",
    "geomorfologia": "geografia física e geologia",
    "relevo": "geografia física e geologia",
    "solo": "geografia física e geologia",
    "intemperismo": "geografia física e geologia",
    "rochas ígneas": "geografia física e geologia",
    "tectônica de placas": "geografia física e geologia",
    "relevo cárstico": "geografia física e geologia",
    "geofísica": "geografia física e geologia",
    "hidrografia": "geografia física e geologia",
    "hidrologia": "geografia física e geologia",
    "dinâmica natural": "geografia física e geologia",
    "solos": "geografia física e geologia",

    "geografia urbana": "geografia humana e urbana",
    "urbanização": "geografia humana e urbana",
    "urbanismo": "geografia humana e urbana",
    "cidades": "geografia humana e urbana",
    "verticalização": "geografia humana e urbana",
    "ambiente urbano": "geografia humana e urbana",
    "espaço geográfico": "geografia humana e urbana",
    "espaço vivido": "geografia humana e urbana",
    "desigualdade socioespacial": "geografia humana e urbana",
    "êxodo urbano": "geografia humana e urbana",
    "dinâmica populacional": "geografia humana e urbana",
    "migração": "geografia humana e urbana",
    "migração nordestina": "geografia humana e urbana",
    "imigração": "geografia humana e urbana",
    "demografia": "geografia humana e urbana",
    "população": "geografia humana e urbana",
    "regatão": "geografia humana e urbana",
    "navegação fluvial": "geografia humana e urbana",
    "espaço público": "geografia humana e urbana",
    "desenvolvimento local": "geografia humana e urbana",
    "sustentabilidade urbana": "geografia humana e urbana",
    "ecologia urbana": "geografia humana e urbana",
    "cidades sustentáveis": "geografia humana e urbana",

    "meio ambiente": "meio ambiente e sustentabilidade",
    "sustentabilidade": "meio ambiente e sustentabilidade",
    "desmatamento": "meio ambiente e sustentabilidade",
    "queimadas": "meio ambiente e sustentabilidade",
    "crise climática": "meio ambiente e sustentabilidade",
    "mudança climática": "meio ambiente e sustentabilidade",
    "mudanças climáticas": "meio ambiente e sustentabilidade",
    "aquecimento global": "meio ambiente e sustentabilidade",
    "Amazônia": "meio ambiente e sustentabilidade",
    "Cerrado": "meio ambiente e sustentabilidade",
    "reserva extrativista": "meio ambiente e sustentabilidade",
    "seringueiros": "meio ambiente e sustentabilidade",
    "Revolução Verde": "meio ambiente e sustentabilidade",
    "agrotóxicos": "meio ambiente e sustentabilidade",
    "degradação": "meio ambiente e sustentabilidade",
    "desastres ambientais": "meio ambiente e sustentabilidade",
    "desastres naturais": "meio ambiente e sustentabilidade",
    "energia renovável": "meio ambiente e sustentabilidade",
    "energia solar": "meio ambiente e sustentabilidade",
    "energia geotérmica": "meio ambiente e sustentabilidade",
    "matriz energética": "meio ambiente e sustentabilidade",
    "agroflorestal": "meio ambiente e sustentabilidade",
    "preservação": "meio ambiente e sustentabilidade",
    "recuperação": "meio ambiente e sustentabilidade",
    "comunidades tradicionais": "meio ambiente e sustentabilidade",
    "saberes tradicionais": "meio ambiente e sustentabilidade",
    "povos indígenas": "meio ambiente e sustentabilidade",
    "direitos indígenas": "meio ambiente e sustentabilidade",
    "quilombolas": "meio ambiente e sustentabilidade",
    "agricultura familiar": "meio ambiente e sustentabilidade",
    "agricultura urbana": "meio ambiente e sustentabilidade",
    "agronegócio": "meio ambiente e sustentabilidade",
    "soja": "meio ambiente e sustentabilidade",
    "função social da terra": "meio ambiente e sustentabilidade",
    "reforma agrária": "meio ambiente e sustentabilidade",
    "campesinato": "meio ambiente e sustentabilidade",
    "persistência ambiental": "meio ambiente e sustentabilidade",
    "poluicao": "meio ambiente e sustentabilidade",
    "desastres": "meio ambiente e sustentabilidade",
    "ambiente": "meio ambiente e sustentabilidade",
    "COP-26": "meio ambiente e sustentabilidade",
    "metais raros": "meio ambiente e sustentabilidade",
    "mineração": "meio ambiente e sustentabilidade",

    "território": "geopolítica e território",
    "territorialização": "geopolítica e território",
    "geopolítica e território": "geopolítica e território",
    "economia internacional": "geopolítica e território",
    "exportações": "geopolítica e território",

    "cartografia": "cartografia",
    "sensoriamento remoto": "cartografia",
    "escala_richter": "cartografia",  # no, already done above
    "orientação espacial": "cartografia",

    "clima": "climatologia",
    "circulação atmosférica": "climatologia",
    "ciclo da água": "climatologia",
    "corrente marinha": "climatologia",
    "precipitação": "climatologia",
    "chuva": "climatologia",
    "corrente oceânica": "climatologia",

    # ── FILOSOFIA E SOCIOLOGIA ────────────────────────────────────────────────
    "filosofia antiga": "filosofia antiga e medieval",
    "filosofia": None,  # too generic, handle per-area
    "pré-socráticos": "filosofia antiga e medieval",
    "Platão": "filosofia antiga e medieval",
    "Aristóteles": "filosofia antiga e medieval",
    "Heráclito": "filosofia antiga e medieval",
    "filosofia medieval": "filosofia antiga e medieval",
    "eudaimonia": "filosofia antiga e medieval",
    "dualismo corpo-alma": "filosofia antiga e medieval",
    "retórica": "filosofia antiga e medieval",
    "virtude": "filosofia antiga e medieval",
    "história da filosofia": "filosofia antiga e medieval",
    "filosofia antiga e medieval": "filosofia antiga e medieval",
    "Roma antiga": "filosofia antiga e medieval",

    "filosofia contemporânea": "filosofia moderna e contemporânea",
    "filosofia moderna": "filosofia moderna e contemporânea",
    "filosofia moderna e contemporânea": "filosofia moderna e contemporânea",
    "Kant": "filosofia moderna e contemporânea",
    "imperativo categórico": "filosofia moderna e contemporânea",
    "David Hume": "filosofia moderna e contemporânea",
    "empirismo": "filosofia moderna e contemporânea",
    "cartesianismo": "filosofia moderna e contemporânea",
    "Foucault": "filosofia moderna e contemporânea",
    "Deleuze": "filosofia moderna e contemporânea",
    "Derrida": "filosofia moderna e contemporânea",
    "Habermas": "filosofia moderna e contemporânea",
    "Marcuse": "filosofia moderna e contemporânea",
    "Escola de Frankfurt": "filosofia moderna e contemporânea",
    "Bauman": "filosofia moderna e contemporânea",
    "Bobbio": "filosofia moderna e contemporânea",
    "Castoriadis": "filosofia moderna e contemporânea",
    "Russell": "filosofia moderna e contemporânea",
    "Quine": "filosofia moderna e contemporânea",
    "Carnap": "filosofia moderna e contemporânea",
    "existencialismo": "filosofia moderna e contemporânea",
    "indução": "filosofia moderna e contemporânea",
    "modernidade": "filosofia moderna e contemporânea",
    "rizoma": "filosofia moderna e contemporânea",
    "Stuart Hall": "filosofia moderna e contemporânea",
    "Wollstonecraft": "filosofia moderna e contemporânea",
    "finitude": "filosofia moderna e contemporânea",
    "utopia": "filosofia moderna e contemporânea",

    "ética": "ética e política",
    "utilitarismo": "ética e política",
    "Bentham": "ética e política",
    "política": "ética e política",
    "democracia": "ética e política",
    "soberania popular": "ética e política",
    "estado": "ética e política",
    "formas de governo": "ética e política",
    "teoria política": "ética e política",
    "direito": "ética e política",
    "direito e justiça": "ética e política",
    "alienação": "ética e política",
    "altruísmo": "ética e política",
    "desobediência civil": "ética e política",
    "justiça": "ética e política",
    "poder": "ética e política",
    "dialética": "ética e política",
    "filosofia política": "ética e política",
    "cosmopolitismo": "ética e política",
    "esfera pública": "ética e política",
    "sociedade civil": "ética e política",
    "historicidade": "ética e política",
    "propaganda": "ética e política",  # in humanas context → politics

    "sociologia": "sociologia e estrutura social",
    "classe operária": "sociologia e estrutura social",
    "capitalismo": "sociologia e estrutura social",
    "trabalho": "sociologia e estrutura social",
    "mercado de trabalho": "sociologia e estrutura social",
    "sindicatos": "sociologia e estrutura social",
    "movimentos sociais": "sociologia e estrutura social",
    "desigualdade": "sociologia e estrutura social",
    "vulnerabilidade social": "sociologia e estrutura social",
    "discriminação": "sociologia e estrutura social",
    "preconceito": "sociologia e estrutura social",
    "discriminação positiva": "sociologia e estrutura social",
    "sociedade industrial": "sociologia e estrutura social",
    "sociologia e estrutura social": "sociologia e estrutura social",
    "classe": "sociologia e estrutura social",
    "disciplina": "sociologia e estrutura social",
    "indústria cultural": "sociologia e estrutura social",
    "modernização": "sociologia e estrutura social",
    "transformação social": "sociologia e estrutura social",
    "relações sociais": "sociologia e estrutura social",
    "anseio": "sociologia e estrutura social",
    "trabalho escravo contemporâneo": "sociologia e estrutura social",

    "cultura": "cultura e identidade",
    "identidade cultural": "cultura e identidade",
    "etnocentrismo": "cultura e identidade",
    "gênero": "cultura e identidade",
    "racismo": "cultura e identidade",
    "feminismo": "cultura e identidade",
    "interseccionalidade": "cultura e identidade",
    "identidade racial": "cultura e identidade",
    "cultura de massa": "cultura e identidade",
    "identidade": "cultura e identidade",
    "hibridismo cultural": "cultura e identidade",
    "multiculturalidade": "cultura e identidade",
    "Milton Santos": "cultura e identidade",
    "etnia": "cultura e identidade",
    "diversidade": "cultura e identidade",
    "cultura urbana": "cultura e identidade",
    "cultura material": "cultura e identidade",
    "identidade linguística": "cultura e identidade",
    "identidade regional": "cultura e identidade",
    "cultura corporal": "cultura e identidade",
    "dança": "cultura e identidade",
    "cinema": "cultura e identidade",
    "teledramaturgia": "cultura e identidade",
    "cultura digital": "cultura e identidade",
    "cultura musical": "cultura e identidade",
    "folclore brasileiro": "cultura e identidade",
    "culinária brasileira": "cultura e identidade",
    "gastronomia": "cultura e identidade",
    "cultura afro-brasileira": "cultura e identidade",
    "apropriação cultural": "cultura e identidade",
    "pós-abolição": "cultura e identidade",
    "povos originários": "cultura e identidade",
    "línguas indígenas": "cultura e identidade",
    "línguas africanas": "cultura e identidade",
    "Chiquinha Gonzaga": "cultura e identidade",
    "memória": "cultura e identidade",
    "Salvador": "cultura e identidade",
    "Mariana": "cultura e identidade",
    "antropofagia": "cultura e identidade",
    "Igreja Católica": "cultura e identidade",
    "intolerância religiosa": "cultura e identidade",
    "sacralidade": "cultura e identidade",
    "preservação cultural": "cultura e identidade",
    "multiculturalidade": "cultura e identidade",
    "diferenças culturais": "cultura e identidade",
    "cultura corporal": "cultura e identidade",

    "direitos humanos": "direitos humanos e cidadania",
    "cidadania": "direitos humanos e cidadania",
    "lei maria da penha": "direitos humanos e cidadania",
    "Constituição de 1988": "direitos humanos e cidadania",
    "violência de gênero": "direitos humanos e cidadania",
    "violencia contra a mulher": "direitos humanos e cidadania",
    "saúde pública": "direitos humanos e cidadania",
    "políticas públicas": "direitos humanos e cidadania",
    "educação": "direitos humanos e cidadania",
    "pedagogia": "direitos humanos e cidadania",
    "assistência": "direitos humanos e cidadania",
    "injustiça epistêmica": "direitos humanos e cidadania",
    "sanitarismo": "direitos humanos e cidadania",
    "planejamento familiar": "direitos humanos e cidadania",
    "deficiência": "direitos humanos e cidadania",
    "transparência": "direitos humanos e cidadania",
    "Lei 10.639": "direitos humanos e cidadania",
    "lei 10.639": "direitos humanos e cidadania",
    "Maria da Penha": "direitos humanos e cidadania",

    "epistemologia": "epistemologia e lógica",
    "filosofia da ciência": "epistemologia e lógica",
    "metafísica": "epistemologia e lógica",

    # ── MISSED TAGS (from warnings) ───────────────────────────────────────────
    # humanas
    "Economia": "sociologia e estrutura social",
    "igreja": "história da cultura e arte",
    "história política": "ética e política",
    "Literatura": "história da cultura e arte",
    "medio-ambiente": "meio ambiente e sustentabilidade",
    "globalização": "geopolítica e relações internacionais",
    "história do corpo": "cultura e identidade",
    "comércio": "geopolítica e território",
    "geografia política": "geopolítica e território",
    "censura": "ética e política",
    "geografia cultural": "cultura e identidade",
    "geografia agrária": "meio ambiente e sustentabilidade",
    "paisagem": "geografia física e geologia",
    "ciência e trabalho": "sociologia e estrutura social",
    "expedições científicas": "história moderna",
    "geografia física": "geografia física e geologia",
    # linguagens
    "memórias": "literatura brasileira",
    "relações interpessoais": "sociologia e estrutura social",
    "função social": "gêneros textuais",
    "ironia": "literatura brasileira",
    "trânsito": "aritmética e números",  # math context
    "incêndio": "gêneros textuais",
    "mercado": "gêneros textuais",
    "indígenas": "cultura e identidade",
    "homenagem": "gêneros textuais",
    "tecnologia em saúde": "comunicação e mídia",
    "arte e ciência": "artes visuais",
    "relação homem-natureza": "meio ambiente e sustentabilidade",
    "humor": "gêneros textuais",
    "sociedade colonial": "história do brasil colonial",
    "corpo feminino": "cultura e identidade",
    # math
    "medidas": "aritmética e números",
    "física matemática": "mecânica newtoniana",
    # nature
    "decomposição": "ecologia",
    "medicamentos": "microbiologia e imunologia",
    "nítrio": "química geral e inorgânica",
    "propriedades dos materiais": "química geral e inorgânica",

    # ── LINGUAGENS ────────────────────────────────────────────────────────────
    "interpretação de texto": "interpretação de texto",
    "interpretação": "interpretação de texto",
    "leitura": "interpretação de texto",
    "leitura e interpretação": "interpretação de texto",
    "coesão": "interpretação de texto",
    "coesão referencial": "interpretação de texto",
    "coesão textual": "interpretação de texto",
    "intertextualidade": "interpretação de texto",
    "argumentação": "interpretação de texto",
    "recursos argumentativos": "interpretação de texto",
    "recursos persuasivos": "interpretação de texto",
    "marcadores discursivos": "interpretação de texto",
    "comparação de textos": "interpretação de texto",
    "discurso": "interpretação de texto",
    "reflexão": "interpretação de texto",
    "corpus": "interpretação de texto",

    "gênero textual": "gêneros textuais",
    "gêneros textuais": "gêneros textuais",
    "gênero literário": "gêneros textuais",
    "gêneros literários": "gêneros textuais",
    "gênero discursivo": "gêneros textuais",
    "gênero carta": "gêneros textuais",
    "gênero cartaz": "gêneros textuais",
    "gênero biografia": "gêneros textuais",
    "gênero resenha": "gêneros textuais",
    "gênero publicitário": "gêneros textuais",
    "gênero multimodal": "gêneros textuais",
    "crônica": "gêneros textuais",
    "poesia": "gêneros textuais",
    "romance": "gêneros textuais",
    "conto": "gêneros textuais",
    "miniconto": "gêneros textuais",
    "soneto": "gêneros textuais",
    "reportagem": "gêneros textuais",
    "verbete": "gêneros textuais",
    "tirinha": "gêneros textuais",
    "bilhete": "gêneros textuais",
    "charge": "gêneros textuais",
    "texto legal": "gêneros textuais",
    "suporte": "gêneros textuais",
    "estrutura textual": "gêneros textuais",
    "características do gênero": "gêneros textuais",
    "finalidade comunicativa": "gêneros textuais",
    "autobiografia": "gêneros textuais",
    "canção": "gêneros textuais",
    "capa de revista": "gêneros textuais",
    "podcast": "gêneros textuais",
    "rap": "gêneros textuais",
    "narrativa": "gêneros textuais",
    "multimodalidade": "gêneros textuais",
    "descrição": "gêneros textuais",
    "gênero no esporte": "gêneros textuais",
    "campanha": "gêneros textuais",

    "linguística": "linguística e variação linguística",
    "variação linguística": "linguística e variação linguística",
    "variação linguística regional": "linguística e variação linguística",
    "norma-padrão": "linguística e variação linguística",
    "registros de língua": "linguística e variação linguística",
    "diversidade linguística": "linguística e variação linguística",
    "patrimônio linguístico": "linguística e variação linguística",
    "preconceito linguístico": "linguística e variação linguística",
    "empréstimo linguístico": "linguística e variação linguística",
    "oralidade": "linguística e variação linguística",
    "oralidade e escrita": "linguística e variação linguística",
    "língua": "linguística e variação linguística",
    "língua portuguesa": "linguística e variação linguística",
    "português brasileiro": "linguística e variação linguística",
    "marcas linguísticas": "linguística e variação linguística",
    "polissemia": "linguística e variação linguística",
    "recursos linguísticos": "linguística e variação linguística",
    "recursos expressivos": "linguística e variação linguística",
    "funções da linguagem": "linguística e variação linguística",
    "linguagem": "linguística e variação linguística",
    "tempos verbais": "linguística e variação linguística",
    "conectivos adversativos": "linguística e variação linguística",
    "palavras intraduzíveis": "linguística e variação linguística",
    "letramento digital": "linguística e variação linguística",
    "tecnologias da escrita": "linguística e variação linguística",
    "escrita digital": "linguística e variação linguística",
    "juridiquês": "linguística e variação linguística",
    "libras": "linguística e variação linguística",
    "dislexia": "linguística e variação linguística",
    "linguagem formal": "linguística e variação linguística",
    "língua espanhola": "língua espanhola",
    "língua inglesa": "língua inglesa",
    "povos Tukano e Kamayurá": "linguística e variação linguística",
    "povos Wajãpi": "linguística e variação linguística",

    "literatura brasileira": "literatura brasileira",
    "literatura": "literatura brasileira",  # default in linguagens
    "literatura contemporânea": "literatura brasileira",
    "realismo": "literatura brasileira",
    "romantismo": "literatura brasileira",
    "Romantismo": "literatura brasileira",
    "simbolismo": "literatura brasileira",
    "regionalismo": "literatura brasileira",
    "poesia contemporânea": "literatura brasileira",
    "impressionismo": "literatura brasileira",
    "minimalismo": "literatura brasileira",
    "Machado de Assis": "literatura brasileira",
    "Clarice Lispector": "literatura brasileira",
    "José de Alencar": "literatura brasileira",
    "Visconde de Taunay": "literatura brasileira",
    "Carmen Dolores": "literatura brasileira",
    "Roseana Murray": "literatura brasileira",
    "Marcelino Freire": "literatura brasileira",
    "Eliana Alves Cruz": "literatura brasileira",
    "Vicente de Carvalho": "literatura brasileira",
    "Castro Alves": "literatura brasileira",
    "Gilka Machado": "literatura brasileira",
    "Ruy Castro": "literatura brasileira",
    "Veríssimo": "literatura brasileira",
    "cronista": "literatura brasileira",
    "função poética": "literatura brasileira",
    "expressividade lírica": "literatura brasileira",
    "exílio": "literatura brasileira",
    "poesia indígena": "literatura brasileira",
    "literatura indígena": "literatura brasileira",
    "inconfidência": "literatura brasileira",
    "luto": "literatura brasileira",
    "solidão": "literatura brasileira",
    "comparação estética": "literatura brasileira",

    "literatura mundial": "literatura mundial",
    "Fernando Pessoa": "literatura mundial",
    "mitologia": "literatura mundial",

    "artes visuais": "artes visuais",
    "arte contemporânea": "artes visuais",
    "arte indígena": "artes visuais",
    "arte afro-brasileira": "artes visuais",
    "arte popular": "artes visuais",
    "escultura": "artes visuais",
    "fotografia": "artes visuais",
    "ilustração": "artes visuais",
    "retrato": "artes visuais",
    "entalhe em madeira": "artes visuais",
    "artes-visuais": "artes visuais",
    "Adriana Varejão": "artes visuais",
    "Dalton Paula": "artes visuais",
    "artesanato": "artes visuais",
    "função da arte": "artes visuais",
    "representação": "artes visuais",

    "música": "música e dança",
    "música e dança": "música e dança",

    "comunicação": "comunicação e mídia",
    "meios de comunicação": "comunicação e mídia",
    "mídia": "comunicação e mídia",
    "mídias sociais": "comunicação e mídia",
    "mídias digitais": "comunicação e mídia",
    "redes sociais": "comunicação e mídia",
    "redes-sociais": "comunicação e mídia",
    "jornalismo": "comunicação e mídia",
    "publicidade": "comunicação e mídia",
    "fake news": "comunicação e mídia",
    "informações falsas": "comunicação e mídia",
    "informação": "comunicação e mídia",
    "notícias": "comunicação e mídia",
    "manipulação": "comunicação e mídia",
    "racismo algorítmico": "comunicação e mídia",
    "acesso digital": "comunicação e mídia",
    "cultura do cancelamento": "comunicação e mídia",
    "rádio": "comunicação e mídia",
    "filmes": "comunicação e mídia",

    "espanhol": "língua espanhola",
    "sociedad": "língua espanhola",

    "inglês": "língua inglesa",

    # ── CROSS-AREA GENERIC TAGS ── drop when no better mapping ────────────────
    "física": None,      # too generic — per-area logic below
    "matemática": None,  # too generic
    "geografia": None,   # too generic
    "história": None,
    "sociedade": None,
    "literatura": None,   # will be reassigned below
    "filosofia": None,
    "tecnologia": None,
    "ciências sociais": None,
    "ciências naturais": None,
    "ciencia": None,
    "ciência": None,
    "biologia": None,
    "Física": None,
    "Ecologia": None,
    "matemática-aplicada": None,
    "humanas": None,
    "linguagens": None,
    "ciencias-da-natureza": None,
    "processos-industriais": None,
    "economia": None,
    "economia local": None,
    "material": None,
    "segurança": None,
    "segurança-aeroportos": None,
    "controle de qualidade": None,
    "nanotecnologia": "biotecnologia",
    "indústria": None,
    "indústria alimentícia": None,
    "arquitetura": None,
    "criptografia": "álgebra",
    "robótica": "álgebra",
    "internet": "comunicação e mídia",
    "massa": "mecânica newtoniana",
    "distância": "mecânica newtoniana",
    "tempo": None,  # too ambiguous
    "alimentação": "fisiologia humana",
    "saúde": "fisiologia humana",
    "saúde mental": "sociologia e estrutura social",
    "saude-mental": "sociologia e estrutura social",
    "medicina": "fisiologia humana",
    "farmacologia": "microbiologia e imunologia",
    "ensaio clínico": "microbiologia e imunologia",
    "toxicidade": "microbiologia e imunologia",
    "toxicologia": "microbiologia e imunologia",
    "inseticida": "ecologia",
    "defensivos agrícolas": "ecologia",
    "agricultura": "ecologia",
    "corrente oceânica": "climatologia",
    "maratonas aquáticas": "fisiologia humana",
    "experimento": None,
    "microscopia": "citologia",
    "desvantagens": None,
    "perspectivas": None,
    "relações": None,
    "correspondência": None,
    "pesquisa acadêmica": None,
    "calendário": "aritmética e números",
    "temperatura": "termologia",
    "oscilações": "mecânica newtoniana",
    "contexto histórico": None,
    "expectativas sociais": "sociologia e estrutura social",
    "estereótipos": "cultura e identidade",
    "representações estereotipadas": "cultura e identidade",
    "comportamento": "sociologia e estrutura social",
    "comportamento geracional": "sociologia e estrutura social",
    "gerações": "sociologia e estrutura social",
    "envelhecimento": "sociologia e estrutura social",
    "envelhecimento populacional": "sociologia e estrutura social",
    "maternidade": "cultura e identidade",
    "casamento": "cultura e identidade",
    "amizade": "cultura e identidade",
    "família": "sociologia e estrutura social",
    "crianças": "direitos humanos e cidadania",
    "primeira infância": "direitos humanos e cidadania",
    "acessibilidade": "direitos humanos e cidadania",
    "inclusão": "direitos humanos e cidadania",
    "saúde pública": "direitos humanos e cidadania",
    "violência": "sociologia e estrutura social",
    "violência urbana": "sociologia e estrutura social",
    "atletas brasileiras": "cultura e identidade",
    "Jogos Olímpicos": "cultura e identidade",
    "olimpismo": "cultura e identidade",
    "olimpíadas": "cultura e identidade",
    "paralimpismo": "cultura e identidade",
    "parasurf": "cultura e identidade",
    "esporte": "cultura e identidade",
    "esporte e aventura": "cultura e identidade",
    "esporte eletrônico": "cultura e identidade",
    "esporte e cultura": "cultura e identidade",
    "lutas": "cultura e identidade",
    "atividade física": "fisiologia humana",
    "educação física": "fisiologia humana",
    "alto rendimento": "fisiologia humana",
    "treinamento": "fisiologia humana",
    "filosofia do esporte": "ética e política",
    "filosofia social": "ética e política",
    "solos": "geografia física e geologia",
    "sono": "fisiologia humana",
    "Bahia": None,
    "Ilha do Ferro": None,
    "Jenipapo-Kanindé": "meio ambiente e sustentabilidade",
    "UNICEF": "direitos humanos e cidadania",
    "Milton Santos": "cultura e identidade",
    "Brasil": None,
    "futebol": "cultura e identidade",
    "soro caseiro": "fisiologia humana",
    "hidratação": "fisiologia humana",
    "água": "meio ambiente e sustentabilidade",
    "bancos": "matemática financeira",
    "internet": "comunicação e mídia",
    "jogos": "análise combinatória",
    "astronomia": "gravitação e astronomia",
    "massa": "mecânica newtoniana",
    "gênero no esporte": "gêneros textuais",
    "crítica social": "sociologia e estrutura social",
    "crítica": "sociologia e estrutura social",
    "crítica à elite": "sociologia e estrutura social",
    "questão social": "sociologia e estrutura social",
    "escravidão": "história do brasil colonial",
    "colonização": "história do brasil colonial",
    "Alzheimer": "fisiologia humana",
    "câncer de mama masculino": "fisiologia humana",
    "pobreza menstrual": "direitos humanos e cidadania",
    "transgênero": "direitos humanos e cidadania",
    "empatia": "sociologia e estrutura social",
    "protagonismo feminino": "cultura e identidade",
    "Mariana": None,
    "multiculturalidade": "cultura e identidade",
    "determinantes sociais": "sociologia e estrutura social",
    "redação": "gêneros textuais",
    "autobiografia": "gêneros textuais",
}

# ── Area-specific overrides ───────────────────────────────────────────────────
# (area, old_tag) → new_tag
AREA_OVERRIDE = {
    ("math", "física"): "mecânica newtoniana",
    ("math", "astronomia"): "gravitação e astronomia",
    ("math", "temperatura"): "aritmética e números",
    ("math", "distância"): "aritmética e números",
    ("math", "massa"): "aritmética e números",
    ("math", "tempo"): "aritmética e números",
    ("math", "velocidade"): "aritmética e números",
    ("math", "matemática"): None,
    ("math", "matemática-aplicada"): None,
    ("math", "resolução de problemas"): "álgebra",
    ("math", "interpretação"): "estatística",
    ("math", "representação"): "estatística",
    ("math", "exportações"): "aritmética e números",
    ("math", "água"): "aritmética e números",
    ("math", "epidemiologia"): "estatística",
    ("math", "microscopia"): "estatística",
    ("math", "energia"): "termoquímica e cinética",
    ("math", "robótica"): "álgebra",
    ("math", "criptografia"): "álgebra",
    ("math", "carboidratos"): "aritmética e números",
    ("math", "defensivos agrícolas"): "aritmética e números",
    ("math", "concentração de soluções"): "aritmética e números",
    ("math", "futebol"): "probabilidade",
    ("math", "jogos"): "análise combinatória",
    ("math", "treinamento"): "aritmética e números",
    ("math", "notas"): "estatística",

    ("nature", "matemática"): None,
    ("nature", "física"): None,
    ("nature", "temperatura"): "termologia",
    ("nature", "energia"): "termoquímica e cinética",
    ("nature", "tempo"): None,
    ("nature", "velocidade"): "mecânica newtoniana",
    ("nature", "reprodução"): "fisiologia humana",
    ("nature", "saúde"): "fisiologia humana",
    ("nature", "saúde pública"): "microbiologia e imunologia",
    ("nature", "medicina"): "fisiologia humana",
    ("nature", "agricultura"): "ecologia",
    ("nature", "leitura de gráficos"): None,  # drop — not a science concept
    ("nature", "logaritmos"): None,
    ("nature", "logaritmo"): None,
    ("nature", "geologia"): "geografia física e geologia",
    ("nature", "solos"): "ecologia",
    ("nature", "solo"): "ecologia",
    ("nature", "água"): "ecologia",
    ("nature", "aquecimento global"): "meio ambiente e sustentabilidade",
    ("nature", "biodiversidade"): "ecologia",
    ("nature", "urbanização"): "ecologia",
    ("nature", "sustentabilidade"): "meio ambiente e sustentabilidade",
    ("nature", "nanotecnologia"): "biotecnologia",
    ("nature", "chuva"): "climatologia",
    ("nature", "corrente marinha"): "climatologia",
    ("nature", "precipitação"): "climatologia",
    ("nature", "propagação"): "ondulatória e acústica",

    ("humanas", "história"): None,  # too generic — already have specific tags
    ("humanas", "filosofia"): None,
    ("humanas", "geografia"): None,
    ("humanas", "literatura"): "história da cultura e arte",
    ("humanas", "arte"): "história da cultura e arte",
    ("humanas", "sociedade"): None,
    ("humanas", "matemática"): None,
    ("humanas", "tecnologia"): "sociologia e estrutura social",
    ("humanas", "saúde pública"): "direitos humanos e cidadania",
    ("humanas", "educação"): "direitos humanos e cidadania",
    ("humanas", "propaganda"): "história do brasil república",
    ("humanas", "exportações"): "geopolítica e território",
    ("humanas", "agricultura"): "meio ambiente e sustentabilidade",
    ("humanas", "representação"): "cultura e identidade",
    ("humanas", "crítica social"): "sociologia e estrutura social",
    ("humanas", "escravidão"): "história do brasil colonial",
    ("humanas", "colonização"): "história do brasil colonial",
    ("humanas", "população"): "geografia humana e urbana",
    ("humanas", "imigração"): "geografia humana e urbana",
    ("humanas", "migração"): "geografia humana e urbana",
    ("humanas", "urbanização"): "geografia humana e urbana",
    ("humanas", "biodiversidade"): "meio ambiente e sustentabilidade",
    ("humanas", "sustentabilidade"): "meio ambiente e sustentabilidade",
    ("humanas", "meio ambiente"): "meio ambiente e sustentabilidade",
    ("humanas", "ambiente"): "meio ambiente e sustentabilidade",
    ("humanas", "Amazônia"): "meio ambiente e sustentabilidade",
    ("humanas", "Cerrado"): "meio ambiente e sustentabilidade",
    ("humanas", "queimadas"): "meio ambiente e sustentabilidade",
    ("humanas", "desmatamento"): "meio ambiente e sustentabilidade",
    ("humanas", "dança"): "história da cultura e arte",
    ("humanas", "museu"): "história da cultura e arte",
    ("humanas", "memória"): "história da cultura e arte",
    ("humanas", "cinema"): "história da cultura e arte",
    ("humanas", "teledramaturgia"): "história da cultura e arte",
    ("humanas", "energia solar"): "meio ambiente e sustentabilidade",
    ("humanas", "energia geotérmica"): "meio ambiente e sustentabilidade",
    ("humanas", "matriz energética"): "meio ambiente e sustentabilidade",
    ("humanas", "candomblé"): "história da cultura e arte",
    ("humanas", "religião"): "história da cultura e arte",
    ("humanas", "trabalho"): "sociologia e estrutura social",

    ("linguagens", "arte"): "artes visuais",
    ("linguagens", "artes visuais"): "artes visuais",
    ("linguagens", "dança"): "música e dança",
    ("linguagens", "música"): "música e dança",
    ("linguagens", "literatura"): "literatura brasileira",
    ("linguagens", "filosofia"): "interpretação de texto",
    ("linguagens", "sociedade"): None,
    ("linguagens", "história"): None,
    ("linguagens", "tecnologia"): "comunicação e mídia",
    ("linguagens", "saúde"): "gêneros textuais",
    ("linguagens", "saúde pública"): "gêneros textuais",
    ("linguagens", "medicina"): "gêneros textuais",
    ("linguagens", "educação"): "gêneros textuais",
    ("linguagens", "políticas públicas"): "gêneros textuais",
    ("linguagens", "crítica social"): "interpretação de texto",
    ("linguagens", "racismo"): "interpretação de texto",
    ("linguagens", "direitos humanos"): "interpretação de texto",
    ("linguagens", "meio ambiente"): "interpretação de texto",
    ("linguagens", "esporte"): "gêneros textuais",
    ("linguagens", "propaganda"): "comunicação e mídia",
    ("linguagens", "comparação"): "interpretação de texto",
    ("linguagens", "representação"): "artes visuais",
    ("linguagens", "memória"): "literatura brasileira",
    ("linguagens", "museu"): "artes visuais",
    ("linguagens", "candomblé"): "cultura e identidade",
    ("linguagens", "cultura"): "cultura e identidade",
    ("linguagens", "identidade cultural"): "cultura e identidade",
    ("linguagens", "imigração"): "cultura e identidade",
    ("linguagens", "diversidade"): "cultura e identidade",
    ("linguagens", "gênero"): "cultura e identidade",
    ("linguagens", "feminismo"): "cultura e identidade",
    ("linguagens", "racismo algorítmico"): "comunicação e mídia",
    ("linguagens", "povos indígenas"): "cultura e identidade",
    ("linguagens", "tradição"): "cultura e identidade",
    ("linguagens", "saberes tradicionais"): "cultura e identidade",
    ("linguagens", "trabalho"): "gêneros textuais",
    ("linguagens", "capitalismo"): "interpretação de texto",
    ("linguagens", "trânsito"): "gêneros textuais",
    ("linguagens", "incêndio"): "gêneros textuais",
    ("linguagens", "mercado"): "gêneros textuais",
    ("linguagens", "ironia"): "literatura brasileira",
    ("linguagens", "humor"): "gêneros textuais",
    ("linguagens", "homenagem"): "gêneros textuais",
    ("linguagens", "função social"): "gêneros textuais",
    ("linguagens", "relações interpessoais"): "interpretação de texto",
    ("linguagens", "corpo feminino"): "cultura e identidade",
    ("linguagens", "sociedade colonial"): "história do brasil colonial",
    ("linguagens", "arte e ciência"): "artes visuais",
    ("linguagens", "tecnologia em saúde"): "comunicação e mídia",
    ("linguagens", "relação homem-natureza"): "meio ambiente e sustentabilidade",
    ("linguagens", "memórias"): "literatura brasileira",
    ("linguagens", "indígenas"): "cultura e identidade",
    ("math", "trânsito"): "aritmética e números",
    ("math", "medidas"): "aritmética e números",
    ("math", "física matemática"): "mecânica newtoniana",
    ("nature", "decomposição"): "ecologia",
    ("nature", "medicamentos"): "microbiologia e imunologia",
    ("nature", "nítrio"): "química geral e inorgânica",
    ("nature", "propriedades dos materiais"): "química geral e inorgânica",
    ("humanas", "Economia"): "sociologia e estrutura social",
    ("humanas", "igreja"): "história da cultura e arte",
    ("humanas", "história política"): "ética e política",
    ("humanas", "Literatura"): "história da cultura e arte",
    ("humanas", "medio-ambiente"): "meio ambiente e sustentabilidade",
    ("humanas", "globalização"): "geopolítica e relações internacionais",
    ("humanas", "história do corpo"): "cultura e identidade",
    ("humanas", "comércio"): "geopolítica e território",
    ("humanas", "geografia política"): "geopolítica e território",
    ("humanas", "censura"): "ética e política",
    ("humanas", "geografia cultural"): "cultura e identidade",
    ("humanas", "geografia agrária"): "meio ambiente e sustentabilidade",
    ("humanas", "paisagem"): "geografia física e geologia",
    ("humanas", "ciência e trabalho"): "sociologia e estrutura social",
    ("humanas", "expedições científicas"): "história moderna",
    ("humanas", "geografia física"): "geografia física e geologia",
    ("linguagens", "movimentos sociais"): "interpretação de texto",
    ("linguagens", "violência"): "interpretação de texto",
}


def remap_tags(tags: list, area: str) -> list:
    new_tags = set()
    for tag in tags:
        # Check area override first
        override_key = (area, tag)
        if override_key in AREA_OVERRIDE:
            result = AREA_OVERRIDE[override_key]
        else:
            result = GENERAL_MAP.get(tag, tag)  # keep if not in map

        if result is not None:
            new_tags.add(result)

    # Filter to only valid unified tags
    valid = new_tags & ALL_VALID
    # Any remaining unmapped tags (not in ALL_VALID) — try to infer
    unknowns = new_tags - ALL_VALID
    if unknowns:
        print(f"  [WARN] Unknown tags after mapping (area={area}): {unknowns}")

    return sorted(valid)


# ─────────────────────────────────────────────────────────────────────────────
# PROCESS ALL FILES
# ─────────────────────────────────────────────────────────────────────────────
changed_total = 0
files = sorted(f for f in glob.glob("public/*.json") if "manifest" not in f and "contexts" not in f)

for filepath in files:
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    questions = data if isinstance(data, list) else data.get("questions", [])
    changed = 0

    for q in questions:
        area = q.get("area", "")
        old_tags = q.get("tags", [])
        new_tags = remap_tags(old_tags, area)

        # Fallback: if no tags mapped, assign area default
        if not new_tags:
            defaults = {
                "math": ["aritmética e números"],
                "nature": ["ecologia"],
                "humanas": ["sociologia e estrutura social"],
                "linguagens": ["interpretação de texto"],
            }
            new_tags = defaults.get(area, [])

        if new_tags != old_tags:
            q["tags"] = new_tags
            changed += 1

    changed_total += changed

    if isinstance(data, list):
        out = data
    else:
        out = data
        out["questions"] = questions

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    print(f"{filepath}: {changed} questions updated")

print(f"\nDone. {changed_total} total questions updated.")
